### ISSUE TITLE
Elastic app plugin to migrate data with kubemove framework

### ISSUE THREAD

**Issue by vishnuitta** [kubemove/kubemove#26]
This issue is to write plugin that KubeMove framework can call to migrate Elastic application's data from source cluster to destination cluster.

**Comment by mynktl** [comment]
For an overview of plugin design/flow, please refer https://github.com/kubemove/kubemove/blob/master/doc/DDM.md.

**Comment by hossainemruz** [comment]
# A High Level Plan to Implement a Elasticsearch Plugin

Here, I am going to draft a high level plan of implementing a Elasticsearch plugin for ECK.

## Assumptions

- Both of the source and destination cluster has ECK operator installed.
- Source cluster can access to destination cluster.
- MINIO server is being used as backend registry.
- DDM can hit destination Elasticsearch api from source cluster.

## Working Process

1. When a user creates MoveEngine for ES, the following things will happen in `INIT` call.
	- Patch source ES CR to inject an `init-container` that will install storage plugin
	- Wait for the source ES to to be ready with the storage plugin.
	- Register the MINIO repository
	- Deploy ES CR with storage plugin installer `init-container` in the destination cluster.
	- Wait for the destination ES to be ready.
	- Register the MINIO registry in the destination ES.
2. Then, on each `SYNC`, DDM of source cluster will do the followings
	- Call Snapshot API of source ES.
	- Wait for Snapshot to be completed.
	- Call restore API of the destination ES.
	- Wait for restore to be completed.

Questions:
1. What will happen in `STATUS` call?
2. Should we wait for restore to complete or that should be checked on `SYNC` call?

**Comment by mynktl** [comment]
In `STATUS` call, DDM will query the sync status. We can wait for restore to complete, but this is an RPC call. So considering timeout and also async `SYNC`,  i have added `STATUS` call.

**Comment by hossainemruz** [comment]
## Implementation Plan

- [x] Preliminaries
	- [x] Explore different ways to connect two local clusters
	- [x] Test accessing a MINIO server (running outside/inside the cluster) from source and destination cluster.
	- [x] Test creating resources in destination cluster from source cluster.
	- [x] Verify patching Elasticsearch does not cause data loss.
	- [x] Understand kubemove code base properly
	- [x] List available Snapshot APIs that might be useful for Kubemove
- [ ] Implementation
	- [x] Make a code level implementation plan
	- [x] Make necessary API changes
	- [x] Write Plugin
	- [x] Write Test
	- [ ] Write Docs (maybe not include full details but enough for other to test)

**Comment by vishnuitta** [comment]
how about starting with a plugin and finalize on parameters for below end points:
```
Create a plugin which have gRPC endpoints for
   - Init
      - Add MinIO repository to ES
   - Sync
      - Call ES Snapshot API
   - Status
      - Call ES Snapshot Status API
```

**Comment by hossainemruz** [comment]
## Relevant ES Snapshot API/Command

### Install Repository Plugin

**S3/Minio:**
Install:
```
sudo bin/elasticsearch-plugin install repository-s3
```
Uninstall:
```
sudo bin/elasticsearch-plugin remove repository-s3
```

**Azure:**
Install:
```

**Comment by hossainemruz** [comment]
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-restore-snapshot.html#_snapshot_status

>The restore operation can be performed on a functioning cluster. However, an existing index can be only restored if it’s closed and has the same number of shards as the index in the snapshot. The restore operation automatically opens restored indices if they were closed and creates new indices if they didn’t exist in the cluster.

We have to close all indexes of the destination ES before restoring.

**Comment by mynktl** [comment]
We can do that. Destination cluster will not be serving IOs to user while syncing. Once user executes `MoveSwitch` from source cluster then only destination cluster will start allowing IOs. So we can close all indexes before restore.

**Comment by hossainemruz** [comment]
## Steps to Move data using Minio

1. Create Secret With Minio Credentials

```
kubectl create secret generic minio-credentials \
 	--from-literal=s3.client.default.access_key=<minio access key> \
	--from-literal=s3.client.default.secret_key=<minio secret key> \
```

2. Create ES CR with Repository Plugin Installer InitContainer

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.5.2
  secureSettings:
  - secretName: minio-credentials
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
```

3. Register Repository

```bash
PUT _snapshot/my_minio_repository
{
  "type": "s3",
  "settings": {
    "bucket": "my_bucket",
	"base_path": "<ES Namespace>/<ES Name>",
	"endpoint": "<minio server address>",
	"protocol": "http", # https not supported for Minio 
	"readonly": "true", # only to destination ES
  }
}
```

4. Take a Snapshot

```bash
PUT /_snapshot/my_minio_repository/snapshot-<timestamp>
```

5. Wait for Snapshot to Success

```bash
GET /_snapshot/my_minio_repository/snapshot-<timestamp>
```

6. Close all open indexes of the destination ES

```bash
POST /_open/_close
```

7. Restore the Snapshot

```bash
POST /_snapshot/my_minio_repository/<snapshot-id>/_restore
```

8. Verify the snapshot has succeeded.

```bash
GET /_recovery
```
or

```bash
GET _cat/recovery?v&h=i,st,snap
```

**Questions?**
1. Should we introduce a retention/cleanup policy to cleanup old snapshots automatically?

Then, we should hit the following API after the Snapshot succeeded.
```bash
DELETE /_snapshot/my_minio_repository/<old snapshot>
```

2. If a snapshot fail to complete, should we delete the failed snapshot?
Then, we should hit the following API

```bash
DELETE /_snapshot/my_minio_repository/<failed snapshot>
```

**Comment by hossainemruz** [comment]
## Code Level Implementation Plan

1. **Init(Params)** call
	- Register Snapshot Repository in the source Elasticsearch.
	- Register Snapshot Repository in the destination Elasticsearch.
2. **Sync(SyncPhase, Params)** call
	- SyncPhase: Backup
		- Hit Snapshot API in the source ES.
	- SyncPhase: Restore
		- Hit Index API in the Destination ES to close all the indexes.
		- Hit Recovery API in the destination ES.
3. **Status(StatusType, SnapshotName, Params)** call
	- StatusType: BackupStatus
		- Hit source ES API to retrieve the Snapshot backup state. 
	- StatusType: RestoreStatus
		- Hit destination ES API to retrieve the Snapshot restore state
